[package]
name = "parti"
version = "0.1.0"
authors = ["ggkuron"]
build = "build.rs"

[dependencies]
gfx = "0.12.0"
gfx_device_gl = "0.11.0"
gfx_window_glutin = "0.12.0"
glutin = "0.6"
collada = "0.3.0"
cgmath = "0.12.0"
rusqlite = "0.7.3"
png = "0.5"
